### ISSUE TITLE
Boilerplate/Wireframe for the page

### ISSUE THREAD

**Issue by Rajashekar-Panuganti** [Rajashekar-Panuganti/Weather-App#2]

**Comment by suhailshaik98** [comment]
Created a wireframe

and also instead of the cards shown on the video, we will be using this 

https://codepen.io/l-ignatova/pen/poKMWLp

https://github.com/Rajashekar-Panuganti/Weather-App/assets/50869059/099aba12-01c5-4186-b264-ef0aed0e9727
